priority_instance_ids:
- django__django-14672
- sphinx-doc__sphinx-10449
- django__django-14493
- django__django-15916
- pytest-dev__pytest-5262
- sphinx-doc__sphinx-8459
- sphinx-doc__sphinx-9281
- django__django-16082
- sympy__sympy-20916
- django__django-14631
- django__django-15930
- django__django-7530
- sympy__sympy-14248
- pylint-dev__pylint-4551
- pallets__flask-5014
- sphinx-doc__sphinx-7440
- sympy__sympy-17655
- django__django-17084
- django__django-16485
- django__django-16901
- django__django-15957
- django__django-13809
- django__django-14608
- django__django-16263
- matplotlib__matplotlib-25332
- sympy__sympy-13551
- django__django-16454
- django__django-14351
- django__django-16116
- django__django-14404
- django__django-15103
- sphinx-doc__sphinx-7985
- django__django-14017
- django__django-14053
- pylint-dev__pylint-6903
- django__django-15037
- django__django-14792
- sympy__sympy-13852
- django__django-15569
- psf__requests-6028
- django__django-15128
- django__django-14559
- django__django-15368
- sympy__sympy-15976
- sympy__sympy-19040
- psf__requests-1766
- pytest-dev__pytest-7205
- sphinx-doc__sphinx-8593
- sphinx-doc__sphinx-8595
- django__django-15315
- pytest-dev__pytest-5631
- django__django-15987
- sympy__sympy-13974
- django__django-16938
- sphinx-doc__sphinx-7910
- sympy__sympy-11618
- pytest-dev__pytest-7521
- sympy__sympy-12096
- django__django-15277
- matplotlib__matplotlib-22871
- django__django-15851
- django__django-15252
- sphinx-doc__sphinx-9591
- sphinx-doc__sphinx-7757
- django__django-14434
- django__django-16502
- django__django-16642
- pylint-dev__pylint-4970
- django__django-14855
- sphinx-doc__sphinx-7748
- django__django-14376
- sphinx-doc__sphinx-7590
- pytest-dev__pytest-8399
- sympy__sympy-23262
- sympy__sympy-12481
- django__django-14534
- django__django-16899
- matplotlib__matplotlib-24026
- sympy__sympy-22080
- django__django-16569
- matplotlib__matplotlib-22865
- sphinx-doc__sphinx-8265
- psf__requests-1724
- django__django-15563
- pylint-dev__pylint-6386
- pylint-dev__pylint-4661
- sympy__sympy-22914
- matplotlib__matplotlib-23299
- matplotlib__matplotlib-13989
- sympy__sympy-19637
- django__django-14122
- sympy__sympy-15349
- django__django-15127
- django__django-14140
- sphinx-doc__sphinx-8551
- matplotlib__matplotlib-25775
- matplotlib__matplotlib-24177
- sympy__sympy-18698
- django__django-15863
- django__django-14155
