_target_: code_obfuscation_research.perturbations.js_rename_symbols.RenameSymbolsJSPerturbation
name: rename_symbols_js_params_only
rename_functions: false
rename_classes: false
rename_parameters: true
